"""Six-input launcher boundary and image/stage/dashboard package provenance."""
import hashlib
import json
import os
from pathlib import Path
import stat
import subprocess
import tempfile
import sys
from types import SimpleNamespace

import pytest

import porota_mode_manager as manager
from cg_paper_workspace import CONTAINER_DB, artifact_root
from rc6_dynamic_universe.promotion import RuntimeCapacityController
from scripts.porota_artifact_provenance import canonical_bytes, create_source_manifest, ProvenanceError
from tests.test_rc6_capacity_promotion import approved, wire


def prepare_launcher(tmp_path, monkeypatch, inputs):
    monkeypatch.setattr(manager, "ROOT", tmp_path)
    monkeypatch.setattr(manager, "DATA", tmp_path / "data")
    monkeypatch.setattr(manager, "env_file", lambda: inputs)
    directory = tmp_path / "data/diagnosticos"; directory.mkdir(parents=True, exist_ok=True)
    (directory / "dashboard_preview_v1633.env").write_text(
        "DASHBOARD_ACCESS_TOKEN=OFFLINE_FIXTURE\nPOROTA_DYNAMIC_CAPACITY_MODE=APPROVED\n"
        "POROTA_SHADOW_RUNTIME_ROOT=/wrong/preview-root\nPOROTA_BUILD_SHA=spoofed\n")


def read_env(path):
    return dict(line.split("=", 1) for line in path.read_text().splitlines() if "=" in line)


@pytest.fixture
def disk_path(monkeypatch):
    # /tmp may be tmpfs even when its size exceeds the runtime's 32 MiB. Use
    # the repository's actual disk mount, with an isolated disposable layout.
    # The production constants remain 1000. GitHub's host runner can be 1001;
    # the synthetic native layout uses its actual owner for O_NOATIME.
    monkeypatch.setattr(manager, "SQLITE_SCRATCH_UID", os.geteuid())
    monkeypatch.setattr(manager, "SQLITE_SCRATCH_GID", os.getegid())
    with tempfile.TemporaryDirectory(prefix="rc6-native-disk-",
                                     dir=Path(__file__).resolve().parents[2]) as directory:
        yield Path(directory)


@pytest.mark.parametrize("mode,status", [("OFF", "OFF_BASELINE"), ("SHADOW", "SHADOW_BASELINE"), ("APPROVED", "APPROVED_DYNAMIC")])
def test_six_inputs_flow_through_canonical_env_into_real_capacity_controller(tmp_path, monkeypatch, wire, mode, status):
    policy, recommendation, report, approval, at = approved(wire)
    policy["mode"] = mode
    inputs = {"POROTA_DYNAMIC_CAPACITY_MODE": mode,
              "POROTA_CAPACITY_SHADOW_PATH": str(artifact_root(CONTAINER_DB) / "dynamic-shadow/CURRENT.json")}
    for key, value in (("POLICY", policy), ("REPORT", report), ("RECOMMENDATION", recommendation), ("APPROVAL", approval)):
        name = f"/app/data/rc6-capacity/{key.lower()}.json"
        inputs["POROTA_CAPACITY_" + key + "_PATH"] = name
        host = tmp_path / name.removeprefix("/app/"); host.parent.mkdir(parents=True, exist_ok=True)
        host.write_text(json.dumps(value))
    prepare_launcher(tmp_path, monkeypatch, inputs)
    observer = manager.observer_runtime_env(); dashboard = manager.dashboard_env("PRODUCTION_PAPER")
    observer_values, dashboard_values = read_env(observer), read_env(dashboard)
    for key in manager.CAPACITY_ENV_KEYS:
        assert observer_values[key] == dashboard_values[key] == inputs[key]
    canonical_root = str(artifact_root(CONTAINER_DB) / "dynamic-shadow")
    assert observer_values["POROTA_DYNAMIC_SHADOW_ROOT"] == dashboard_values["POROTA_SHADOW_RUNTIME_ROOT"] == canonical_root
    assert stat.S_IMODE(observer.stat().st_mode) == stat.S_IMODE(dashboard.stat().st_mode) == 0o600
    # This mapping is the isolated fixture's /app mount. Controller reads the
    # real files produced above, using the exact env generated by the launcher.
    mounted_env = dict(observer_values)
    for key in manager.CAPACITY_ENV_KEYS[1:]:
        if mounted_env[key]: mounted_env[key] = str(tmp_path / mounted_env[key].removeprefix("/app/"))
    resolved = RuntimeCapacityController(environ=mounted_env).state(at)
    assert resolved["status"] == status
    assert resolved["real_orders_sent"] == 0


def test_shipped_configuration_and_missing_inputs_never_autoactivate(tmp_path, monkeypatch):
    prepare_launcher(tmp_path, monkeypatch, {})
    values = read_env(manager.observer_runtime_env())
    assert values["POROTA_DYNAMIC_CAPACITY_MODE"] == "OFF"
    assert all(key in values for key in manager.CAPACITY_ENV_KEYS)
    for key in ("REPORT", "RECOMMENDATION", "APPROVAL"):
        assert values["POROTA_CAPACITY_" + key + "_PATH"] == ""
    with pytest.raises(ValueError, match="INPUT_REQUIRED"):
        manager.dynamic_capacity_settings({"POROTA_DYNAMIC_CAPACITY_MODE": "APPROVED"})


@pytest.mark.parametrize("key,value", [
    ("POROTA_DYNAMIC_CAPACITY_MODE", "LIVE"),
    ("POROTA_CAPACITY_POLICY_PATH", "/app/ops/policy/../secret.json"),
    ("POROTA_CAPACITY_REPORT_PATH", "/run/secrets/SYNTHETIC_SECRET.json"),
    ("POROTA_CAPACITY_REPORT_PATH", "/app/data/rc6-capacity/a.json\nPPI_TOKEN=SYNTHETIC_SECRET"),
    ("POROTA_CAPACITY_SHADOW_PATH", "/app/data/rc6-capacity/foreign-shadow"),
    ("POROTA_DYNAMIC_SHADOW_ROOT", "/wrong/root"),
])
def test_invalid_config_is_rejected_without_echoing_sensitive_values(tmp_path, monkeypatch, key, value):
    prepare_launcher(tmp_path, monkeypatch, {key: value})
    with pytest.raises(ValueError) as raised:
        manager.observer_runtime_env()
    assert "SYNTHETIC_SECRET" not in str(raised.value)
    assert not (tmp_path / "data/diagnosticos/observer_runtime_v17.env").exists()


def test_config_symlink_parent_and_world_writable_input_are_rejected(tmp_path, monkeypatch):
    path = tmp_path / "data/rc6-capacity/report.json"; path.parent.mkdir(parents=True)
    path.write_text("{}")
    prepare_launcher(tmp_path, monkeypatch, {"POROTA_CAPACITY_REPORT_PATH": "/app/data/rc6-capacity/report.json"})
    path.chmod(0o666)
    with pytest.raises(ValueError, match="UNSAFE_OR_UNAVAILABLE"):
        manager.observer_runtime_env()
    path.chmod(0o644); path.unlink(); path.symlink_to(tmp_path / "outside.json")
    with pytest.raises(ValueError, match="SYMLINK"):
        manager.observer_runtime_env()


def source_fixture(tmp_path, monkeypatch):
    monkeypatch.setattr(manager, "ROOT", tmp_path)
    for relative in manager.DASHBOARD_RUNTIME_SOURCES:
        path = tmp_path / relative
        if relative == "rc6_trader_dashboard": path = path / "__init__.py"
        path.parent.mkdir(parents=True, exist_ok=True); path.write_bytes(b"# immutable source fixture\n")
    (tmp_path / "rc6_trader_dashboard/projection.py").write_bytes(b"# immutable projection fixture\n")
    policy_root = tmp_path / "ops/policy"; policy_root.mkdir(parents=True)
    (policy_root / "rc6-dynamic-capacity-v1.json").write_bytes(b'{"mode":"OFF"}\n')
    for args in (("init", "-q"), ("config", "user.name", "Offline fixture"), ("config", "user.email", "fixture@example.invalid"),
                 ("add", "."), ("commit", "-qm", "exact dashboard mount source")):
        subprocess.run(["git", "-C", str(tmp_path), *args], check=True, capture_output=True)
    manifest = create_source_manifest(tmp_path); raw = canonical_bytes(manifest)
    (tmp_path / "POROTA_SOURCE_PROVENANCE.json").write_bytes(raw)
    labels = {"porota.commit": manifest["candidate_sha"], "porota.tree": manifest["candidate_tree_sha"],
              "porota.source-manifest-sha256": hashlib.sha256(raw).hexdigest(), "porota.predeploy": "v2"}
    calls = []
    def run(*args, **kwargs):
        calls.append(args)
        return SimpleNamespace(stdout=json.dumps(labels))
    monkeypatch.setattr(manager, "run", run)
    return manifest, labels, calls


def test_package_and_hook_match_same_image_source_before_container_mutation(tmp_path, monkeypatch):
    manifest, labels, calls = source_fixture(tmp_path, monkeypatch)
    identity = manager.verify_dashboard_source_identity(manager.DASHBOARD_RUNTIME_SOURCES)
    assert identity["candidate_sha"] == manifest["candidate_sha"]
    assert manager._runtime_build_identity()["POROTA_CANDIDATE_TREE_SHA"] == manifest["candidate_tree_sha"]
    assert all(call[:3] == ("docker", "image", "inspect") for call in calls)
    (tmp_path / "rc6_trader_dashboard/__init__.py").write_bytes(b"# stale package\n")
    with pytest.raises(RuntimeError, match="PROVENANCE_MISMATCH"):
        manager.verify_dashboard_source_identity(manager.DASHBOARD_RUNTIME_SOURCES)
    assert not any("rm" in call for call in calls)


def test_correct_files_with_wrong_image_source_labels_are_rejected(tmp_path, monkeypatch):
    _, labels, _ = source_fixture(tmp_path, monkeypatch)
    labels["porota.commit"] = "f" * 40
    with pytest.raises(ProvenanceError, match="IMAGE_LABEL_MISMATCH"):
        manager.verify_dashboard_source_identity(manager.DASHBOARD_RUNTIME_SOURCES)


@pytest.mark.parametrize("mutation", ["missing_module", "extra_module", "hardlink", "world_writable", "metadata_mode"])
def test_mount_package_is_complete_and_all_regular_modes_and_aliases_are_checked(tmp_path, monkeypatch, mutation):
    _, _, calls = source_fixture(tmp_path, monkeypatch)
    package = tmp_path / "rc6_trader_dashboard"
    if mutation == "missing_module": (package / "projection.py").unlink()
    elif mutation == "extra_module": (package / "untracked.py").write_bytes(b"# unknown\n")
    elif mutation == "hardlink": os.link(package / "projection.py", tmp_path / "outside-link")
    elif mutation == "world_writable": (package / "projection.py").chmod(0o666)
    elif mutation == "metadata_mode": (tmp_path / "POROTA_SOURCE_PROVENANCE.json").chmod(0o666)
    with pytest.raises(RuntimeError):
        manager.verify_dashboard_source_identity(manager.DASHBOARD_RUNTIME_SOURCES)
    assert not any("rm" in call or "run" in call for call in calls)


def test_actual_launcher_argv_mounts_validated_input_roots_readonly_for_both_children(disk_path, monkeypatch):
    tmp_path = disk_path
    source_fixture(tmp_path, monkeypatch)
    report = tmp_path / "data/rc6-capacity/report.json"; report.parent.mkdir(parents=True); report.write_text("{}")
    prepare_launcher(tmp_path, monkeypatch, {"POROTA_CAPACITY_REPORT_PATH": "/app/data/rc6-capacity/report.json"})
    secret = tmp_path / ".secrets/ppi_production.json"; secret.parent.mkdir(); secret.write_text("{}")
    calls = []
    def docker(*args, **kwargs):
        calls.append(args)
        if args[:3] == ("docker", "image", "inspect"):
            source = json.loads((tmp_path / "POROTA_SOURCE_PROVENANCE.json").read_text())
            labels = {"porota.commit": source["candidate_sha"], "porota.tree": source["candidate_tree_sha"],
                "porota.predeploy": "v2", "porota.source-manifest-sha256": hashlib.sha256(canonical_bytes(source)).hexdigest()}
            return SimpleNamespace(stdout=json.dumps(labels))
        if args[:3] == ("docker", "inspect", "-f"): return SimpleNamespace(stdout="running")
        if args[:3] == ("docker", "exec", "porota_production_observer"):
            path = tmp_path / args[-1].removeprefix("/app/")
            return SimpleNamespace(stdout=hashlib.sha256(path.read_bytes()).hexdigest() + "  fixture")
        return SimpleNamespace(stdout="synthetic-container-id")
    # The two observer invariant modules are fixture-only; no source/provider
    # runtime is launched. Native Docker argv is captured at the real call site.
    for name in ("cf_intraday_scalping.py", "co_market_sessions_hf6.py"):
        (tmp_path / name).write_bytes(b"# fixture\n")
    monkeypatch.setattr(manager, "run", docker)
    monkeypatch.setattr(manager, "stop_engines", lambda *args, **kwargs: None)
    monkeypatch.setattr(manager, "write_mode", lambda *args, **kwargs: None)
    monkeypatch.setattr(manager, "notify", lambda *args, **kwargs: "OFFLINE")
    manager.simulation()
    launchers = [args for args in calls if args[:3] == ("docker", "run", "-d")]
    assert len(launchers) == 2
    for args in launchers:
        assert f"type=bind,src={tmp_path}/ops/policy,dst=/app/ops/policy,readonly" in args
        assert f"type=bind,src={tmp_path}/data/rc6-capacity,dst=/app/data/rc6-capacity,readonly" in args
        assert f"{tmp_path}/data:/app/data" in args


@pytest.mark.parametrize("configured,expected", [(None, "ENABLED"), (" enabled ", "ENABLED"),
                                                ("OFF", "OFF"), ("disabled", "DISABLED")])
def test_contract_evidence_env_forwarding_preserves_default_and_disabled_native_runner_boundary(
        tmp_path, monkeypatch, configured, expected):
    inputs = {} if configured is None else {"POROTA_CONTRACT_EVIDENCE_MODE": configured}
    prepare_launcher(tmp_path, monkeypatch, inputs)
    values = read_env(manager.observer_runtime_env())
    assert values.get("POROTA_CONTRACT_EVIDENCE_MODE") == expected
    if expected == "ENABLED":
        return  # Positive forwarding; this case never requests provider work.
    program = '''
import ck_contract_evidence_runner_hf6 as runner
def forbidden(*args, **kwargs):
    raise AssertionError("DISABLED_RUNNER_MUST_NOT_OPEN_SOURCE_OR_PROVIDER")
runner.Store=forbidden
runner.observer_state=forbidden
runner.ProductionMarketReader=forbidden
assert runner.CONTRACT_EVIDENCE_MODE in {"OFF","DISABLED"}
assert runner.main() == 0
'''
    result = subprocess.run([sys.executable, "-c", program],
        cwd=Path(__file__).resolve().parents[1], env={**os.environ, **values},
        capture_output=True, text=True, timeout=20)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "STATUS=SKIPPED_SOURCE_UNAVAILABLE_BY_SCOPE" in result.stdout
    assert "PROFILE_PRESERVED=YES" in result.stdout
