"""Arithmetic and static evidence inventory only; no RC6 producer is invoked.

Run: python -B docs/governance/rc6-controlled-architecture-20261009/reproduce.py
      --output-dir /tmp/rc6-controlled-analysis
Optional --hash-pr476 streams the original Git blobs into a SHA256 join index.
Optional --check-prospective-base SHA reports a separate evidence-policy guard.
No network, pytest, SQLite connections, ROOT, Docker, backend or financial tick.
"""
from __future__ import annotations

import argparse
from collections import Counter, defaultdict
import csv
from datetime import datetime, timedelta, timezone
import hashlib
import io
import json
from pathlib import Path
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[3]
PREVIOUS = ROOT / "docs/governance/rc6-systemic-review-20261008"
BASE = "215169ecd0f71d3b293304c7976be2593efdc043"
CODE = "ecad18b6010e3b7e874a00edc72644b3dcc78790"
PR476 = "dfc240a478cf08e0c6a9b0ba1b760307b09a9565"
HISTORICAL = "af08c82ca211e74bb4e5c00d9010af21313814a9"
LIMIT = 512 * 1024**2
BLOCK = 4096  # Canonical contract, never a measurement of the caller's FS.
GENERATED_ROOTS = ("notes/rc6-evidence/", "rc6_audit_evidence/history_convergence/")
DEPLOY_EXCLUSIONS_PROPOSED = (*GENERATED_ROOTS, "rc6_audit_evidence/HISTORY_CONVERGENCE.md")
HELPERS = {"__init__.py", "sqlite_snapshot.py", "sqlite_scratch.py", "package.py", "recompute.py", "history_probe.py"}


def sha(raw):
    return hashlib.sha256(raw).hexdigest()


def document(path):
    return json.loads(path.read_bytes())


def git(*args):
    return subprocess.check_output(["git", "--no-replace-objects", "-C", str(ROOT), *args],
        env={**__import__("os").environ, "GIT_NO_LAZY_FETCH": "1", "GIT_OPTIONAL_LOCKS": "0"})


def proposed_exclusion(path):
    return any(path.startswith(prefix) for prefix in GENERATED_ROOTS) or path == DEPLOY_EXCLUSIONS_PROPOSED[-1]


def evidence_guard(paths):
    """Prospective role rule only; it is NOT a G0--G8 qualification gate.

    These two roots are declared generated evidence/probe custody roles, not
    runtime code. Existing baseline blobs are grandfathered and never deleted.
    Genuine fixtures belong in tests/fixtures with their provenance preserved.
    New generated bytes require an external verified destination, not a commit
    to these bulk roots. Index updates belong in concise governance indices.
    """
    return {"status": "BLOCK_EVIDENCE_POLICY" if any(proposed_exclusion(p) for p in paths) else "PASS",
        "paths_requiring_custody_instead_of_new_git_payload": sorted(p for p in paths if proposed_exclusion(p)),
        "is_material_gate": False, "deletion_authorized": False, "installed_in_CI": False}


def calculate():
    prior = document(PREVIOUS / "horizon-analysis.json")
    cuts = list(csv.DictReader((PREVIOUS / "horizon-measured-cuts.csv").open()))
    pre = datetime(2026, 10, 5, 13, 20, tzinfo=timezone.utc)
    start = pre + timedelta(minutes=15)
    clocks = [pre, *[start + timedelta(seconds=30*i) for i in range(1201)]]
    phases = ["PREOPEN", *["OPEN" if t < t.replace(hour=20, minute=0, second=0) else "CLOSED" for t in clocks[1:]]]
    counts = Counter(phases)
    assert counts == {"PREOPEN": 1, "OPEN": 770, "CLOSED": 431}
    assert len(cuts) == prior["measured_cuts"] == 1049
    assert int(cuts[-1]["archive_allocated_bytes"]) == prior["last_committed_archive"]["allocated_bytes_including_directories"]
    assert sum(int(c["increment_bytes"]) for c in cuts) == 535801856
    assert all(int(c["sequence"]) == i and c["as_of"] == clocks[i-1].isoformat() and c["phase"] == phases[i-1]
               for i, c in enumerate(cuts, 1))
    assert all(int(c["archive_entries"]) == 3*int(c["sequence"])+2 for c in cuts)
    cutoff_final = clocks[-1] - timedelta(hours=10)
    eligible = [i for i, t in enumerate(clocks) if t < cutoff_final]
    assert eligible == [0] and cutoff_final == start
    first_pre_eligible = next(t for t in clocks if pre < t-timedelta(hours=10))
    assert first_pre_eligible.isoformat() == "2026-10-05T23:20:30+00:00"
    boundaries = [c for c in cuts if c["as_of"] in
        {"2026-10-05T20:00:00+00:00", "2026-10-05T20:00:30+00:00"}]
    assert len(boundaries) == 2 and [int(c["projection_bytes"]) for c in boundaries] == [1904640, 4136960]
    reported_total, premium = 500195328, 1777664-442368
    fallback_allowance = (LIMIT-reported_total)//premium
    assert fallback_allowance == 27 and reported_total+28*premium > LIMIT
    fixed_closed = sum(p == "CLOSED" and seq % 32 == 0 for seq, p in enumerate(phases, 1))
    assert fixed_closed == 13
    reserve = 4*65536 + 6*BLOCK + 2*256*1024 + 8192
    assert reserve == 819200
    # This is an envelope counterexample, not an assertion that the native
    # producer actually chooses 431 independent anchors at these measured costs.
    all_closed_independent_comparison = counts["CLOSED"] * 1777664
    assert all_closed_independent_comparison == 766173184 > LIMIT
    # A per-page CAS split without a deduplication proof cannot certify its
    # existing catalog cap. An upper bound exceeding the cap is not a lower
    # bound on actual growth; no impossible-WIP assertion follows from it.
    per_page_parts_possible = len(clocks)*(4050944//BLOCK+2)
    assert per_page_parts_possible > 524288
    assert not proposed_exclusion("rc6_audit_evidence/sqlite_snapshot.py")
    assert not proposed_exclusion("rc6_audit_evidence/__init__.py")
    assert evidence_guard(["tests/fixtures/native.py.source"])["status"] == "PASS"
    assert evidence_guard(["notes/rc6-evidence/new/raw.json"])["status"] == "BLOCK_EVIDENCE_POLICY"
    assert evidence_guard(["rc6_audit_evidence/sqlite_snapshot.py"])["status"] == "PASS"
    policy = document(ROOT / "ops/policy/rc6-heavy-test-governance-v1.json")
    floor = policy["runner"]["official_standard_baseline"]["storage_gib"] * 1024**3
    residual = policy["local_capacity"]["residual_reserve_bytes"]
    assert floor == 14*1024**3 and residual == 4*1024**3 and 26*1024**3+residual > floor
    result = {"schema": "rc6.controlled-architecture-analysis.v1", "code_sha": CODE,
        "historical_sha": HISTORICAL, "document_base_sha": BASE,
        "scope": "STATIC_ARITHMETIC_AND_GIT_BLOBS_ONLY", "financial_workload_executed": False,
        "native_filesystem_or_custody_validated": False, "qualification_claimed": False,
        "g0": {"selected_architecture": "B_NATIVE_AGGREGATE_FILESYSTEM_QUOTA",
            "status": "BLOQUEADO_PREREQUISITES", "canonical_floor_bytes": floor,
            "backing_bytes": 26*1024**3, "project_cap_bytes": 20*1024**3,
            "independent_reserve_bytes": residual, "minimum_before_controls_bytes": 30*1024**3,
            "compound_bootstrap_bound_bytes": None, "root_startup_and_fin_proved": False},
        "g5": {"status": "BLOQUEADO_GLOBAL_BOUND", "limit_bytes": LIMIT,
            "schedule": {"cuts": len(clocks), "counts": dict(counts), "last": clocks[-1].isoformat(),
                "cutoff_at_last": cutoff_final.isoformat(), "operational_cuts_eligible_by_age": 0,
                "only_possible_expired_index": 0, "earliest_strict_preopen_expiry": first_pre_eligible.isoformat()},
            "historical_prefix": {"cuts": 1049, "committed_allocated_bytes": 535801856,
                "peak_allocated_bytes": 535810048, "gc_deleted": 0,
                "native_result_sha256": prior["measured_native_result_sha256"],
                "native_failure": "RETENTION_ARCHIVE_CAPACITY_REACHED", "completion_impossible_without_change": True},
            "conditional_forecast_rejected": {"bytes": reported_total, "fixed_closed_anchors": fixed_closed,
                "fallback_count_bound": None, "extra_anchor_premium_bytes": premium,
                "first_extra_anchor_count_exceeding_limit": 28,
                "all_closed_independent_comparison_bytes": all_closed_independent_comparison,
                "comparison_is_original_workload_prediction": False},
            "fixed_simultaneous_admission_control_reserve_bytes": reserve,
            "blind_per_page_partition_rejected": {"possible_components_bound": per_page_parts_possible,
                "native_catalog_cap": 524288, "actual_unique_components_claimed": False},
            "global_complete_physical_upper_bound_bytes": None, "wip_mathematically_impossible_claimed": False,
            "missing_proofs": ["all1202_original_member_envelopes_and_entropy",
                "effective_codec_choices_including_every_fallback", "CAS_reuse_and_persistent_recipe_indices",
                "directory_physical_allocation_bound", "concurrent_temp_and_recovery_footprint"],
            "GC_credit_used_for_certification_bytes": 0},
        "real_orders_sent": 0, "real_routes": "NOT_CALLED", "ppi_watch": "UNTOUCHED"}
    schedule = [{"sequence": i, "as_of": t.isoformat(), "phase": phase,
        "fixed_mod32_anchor": int(i % 32 == 0), "original_operational_catalog": 1200,
        "observations": 6000, "cohorts_at_transition": "6000_AFTER_SECOND_BOUNDARY" if t >= clocks[772] else "NATIVE_PHASE_SPECIFIC",
        "expiry_credit_bytes": 0} for i, (t, phase) in enumerate(zip(clocks, phases), 1)]
    return result, schedule


def eligible_roots():
    sys.path.insert(0, str(ROOT))
    from scripts.porota_artifact_provenance import dockerignore_exclusion, is_bundle_path
    ignore = (ROOT / ".dockerignore").read_text()
    paths = git("ls-tree", "-r", "--name-only", CODE).decode().splitlines()
    rows = []
    for path in paths:
        if not path.startswith(("notes/", "rc6_audit_evidence/")):
            continue
        raw = (ROOT / path).read_bytes()
        role = ("SOFTWARE_HELPER_KEEP" if path.startswith("rc6_audit_evidence/") and path.split("/")[-1] in HELPERS
                else "TEST_PROBE_SOURCE_KEEP_IN_SOURCE" if path.endswith(".py")
                else "RCA_KEEP_IN_GIT_NOT_BUNDLE" if path.endswith(".md") else "GENERATED_EVIDENCE_PRESERVE")
        rows.append({"path": path, "bytes": len(raw), "sha256": sha(raw), "role": role,
            "native_bundle_eligible": is_bundle_path(path), "native_context_eligible": dockerignore_exclusion(path, ignore) is None,
            "proposed_deploy_exclusion": proposed_exclusion(path), "unique_evidence": "NO_VERIFICADO_PRESERVE",
            "custody": "GIT_AT_"+CODE})
    assert len(rows) == 36 and sum(r["bytes"] for r in rows) == 6658367
    assert all(r["native_bundle_eligible"] and r["native_context_eligible"] for r in rows)
    assert sum(not r["proposed_deploy_exclusion"] for r in rows) == 6
    assert sum(r["bytes"] for r in rows if not r["proposed_deploy_exclusion"]) == 116679
    return rows


def hash_original_blobs(destination):
    rows = list(csv.DictReader((PREVIOUS / "pr476-complete-inventory.csv").open()))
    ids = Counter(r["head_blob_sha1"] for r in rows if r["head_blob_sha1"])
    expected = {r["head_blob_sha1"]: int(r["head_logical_bytes"]) for r in rows if r["head_blob_sha1"]}
    # Verify membership in the original PR476 tree; a hash-shaped string is
    # insufficient. Do not use modified WIP bytes for the old path inventory.
    tree = {}
    for item in git("ls-tree", "-r", "-z", PR476).split(b"\0"):
        if item:
            metadata, path = item.split(b"\t", 1); tree[path.decode()] = metadata.split()[2].decode()
    assert len(rows) == 3127 and all(tree.get(r["path"]) == r["head_blob_sha1"] for r in rows if r["head_blob_sha1"])
    with tempfile.TemporaryFile() as queue, destination.open("w", newline="") as target:
        queue.write("".join(oid+"\n" for oid in sorted(ids)).encode()); queue.seek(0)
        process = subprocess.Popen(["git", "--no-replace-objects", "-C", str(ROOT), "cat-file", "--batch"],
            stdin=queue, stdout=subprocess.PIPE)
        writer = csv.writer(target, lineterminator="\n"); writer.writerow(["git_blob_sha1", "bytes", "sha256", "path_copies_in_previous_inventory"])
        for oid in sorted(ids):
            header = process.stdout.readline().decode().strip().split()
            assert len(header) == 3 and header[:2] == [oid, "blob"] and int(header[2]) == expected[oid]
            size = int(header[2]); digest = hashlib.sha256(); git_digest = hashlib.sha1(b"blob "+str(size).encode()+b"\0")
            remaining = size
            while remaining:
                raw = process.stdout.read(min(1024**2, remaining)); assert raw
                remaining -= len(raw); digest.update(raw); git_digest.update(raw)
            assert process.stdout.read(1) == b"\n" and git_digest.hexdigest() == oid
            writer.writerow([oid, size, digest.hexdigest(), ids[oid]])
        assert process.stdout.read() == b"" and process.wait() == 0
    return {"paths": len(rows), "unique_head_blobs": len(ids), "sha256_join_index": destination.name,
        "join_to": "../rc6-systemic-review-20261008/pr476-complete-inventory.csv",
        "original_tree_membership_and_blob_sha1_verified": True, "sha256": sha(destination.read_bytes())}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--hash-pr476", action="store_true")
    parser.add_argument("--check-prospective-base")
    args = parser.parse_args(); output = args.output_dir.resolve(); output.mkdir(parents=True, exist_ok=True)
    result, schedule = calculate(); roots = eligible_roots()
    result["eligible_evidence_roots"] = {"files": len(roots), "bytes": sum(r["bytes"] for r in roots),
        "keep_software_files": 6, "keep_software_bytes": 116679, "proposed_excluded_files": 30,
        "proposed_excluded_bytes": 6541688, "actual_image_inspected": False}
    with (output / "horizon-schedule.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(schedule[0]), lineterminator="\n");writer.writeheader();writer.writerows(schedule)
    (output / "evidence-roots.json").write_text(json.dumps(roots, indent=2, sort_keys=True)+"\n")
    if args.hash_pr476:
        result["pr476_sha256_custody_index"] = hash_original_blobs(output / "pr476-blob-sha256.csv")
    if args.check_prospective_base:
        paths = git("diff", "--name-only", "--diff-filter=AM", args.check_prospective_base, "HEAD").decode().splitlines()
        result["prospective_evidence_guard"] = evidence_guard(paths)
    (output / "analysis.json").write_text(json.dumps(result, indent=2, sort_keys=True)+"\n")
    print(json.dumps({"analysis": "PASS_ARITHMETIC_AND_STATIC_ONLY", "G0": result["g0"]["status"],
        "G5": result["g5"]["status"], "qualification": False, "outputs": sorted(p.name for p in output.iterdir())}, sort_keys=True))


if __name__ == "__main__":
    main()
